### ISSUE TITLE
Is there any way supporting Mac OS Big Sur

### ISSUE THREAD

**Issue by chengyingyuan** [Am1nCmd/Dell-Inspiron-14-7447-Pandora-Hackintosh#15]
I can run Catalina (10.15.7) smoothly using this project except intel wifi card. After updated driver of AirportItlwm ( https://github.com/OpenIntelWireless/itlwm ), it works perfectly. But it cannot boot Mac OS Big Sur, leaving me a blank screen with message saying "Please contact apple help" .  Is there any way booting Big Sur?

**Comment by Am1nCmd** [comment]
Hello there. Sorry for late reply

I’m not using Big Sur and not interested into it since performance was really bad for me. So I’ll stay on Mojave or Catalina. But, I’ll update my config using Clover and the new one using OpenCore. Hopefully it support for Big Sur. You can try it later

Sent from my iPhone

On 16 Jan 2021, at 6.17 PM, Yingyuan Cheng <notifications@github.com> wrote:

﻿

I can run Catalina (10.15.7) smoothly using this project except intel wifi card. After updated driver of AirportItlwm ( https://github.com/OpenIntelWireless/itlwm ), it works perfectly. But it cannot boot Mac OS Big Sur, leaving me a blank screen with message saying "Please contact apple help" . Is there any way booting Big Sur?

**Comment by chengyingyuan** [comment]
I'm very glad to hear that, and looking forward to new one.

**Comment by rahills** [comment]
I installed Big Sur with Olarila vanilla image and OpenCore bootloader. You can use my EFI to boot Big Sur: https://github.com/rahills/Dell-Inspiron-7447-Pandora-Hackintosh-macOS-Big-Sur-with-OpenCore
